sudo: required
services:
- docker
language: go
go:
- 1.7.3
before_install:
- bin/ci-setup
install:
- bundle
- "./bin/vendor-check"
script:
- make -j2 test
- make reject-wip
- bundle exec danger
after_script:
- docker ps || true
- docker logs testregistry_slave_1 || true
after_success:
- make coverage
- bin/codecov -f /tmp/sous-cover/count_merged.txt
env:
  global:
  - GIT_AUTHOR_NAME=SousCI
  - GIT_COMMITTER_NAME=SousCI
  - GIT_AUTHOR_EMAIL=sous@nowhere.in.particular.com
  - GIT_COMMITTER_EMAIL=sous@nowhere.in.particular.com
  - DOCKER_VERSION=1.10.3~trusty
  - DOCKER_COMPOSE_VERSION=1.9.0
  - VERBOSE=1
  - secure: jQv4im3Imakryl54Z7qR2BEa1+Gq//sAwo3XP/1J6sSdtBjtOYY1SgdAYh7pVB111HV546vKPJqQ6GsAtHM7tjnVjlF1PabAHEWl/ZP3ZXj3SvuFNaV5j5PmrJvxPlK7nbr0uG6PPspxFkZg+X87GGIyFGCp7F3EWKIU6aX6rEeBbY/greAxISmtGYHrDwK4sQnMXl4+WoagbKwoi16fK94XweU2Etg40rLwtYRdRJTPMdhrinkkkfQ4Jga5uepsmkZFjgZJySgyEzxvVuUuEYHaQreRLHzJBjPXw96tQOGpw4OT5aRJjga6PlEJRp68pC3KPrzW7lQQMMCHpxrauEqR1r1ltg+UD2GIixAT80duOl7mD6aPyx3L04L/bg4u1sI26JyHN34X/mpg9OufE47zSOC48RicSA6y4D+ZyD/dubu626NScnLufAveWaVH/mu5brVZ3ni+8BgVqDW/vfIJTyELegz7DD9wS/xaoUVnAjnTH73efce8bDAaAOvpa4dlkZEcBDU2LjasP735FNh0/sLeVsuwhopMIKPsnpwce1Fxg83ls+KRDqXj8/l67Db5nQqTvsWk3S12nvrgPO1uX/we8fqwUKuLNlnU3befd7KugvUamixGoxlX65etwt4hvFWT11Qfv/IB7JXjLToUAfXm/QpiprEm/VqZWTM=
  - secure: yoQHrMJeCnRumhKPRCvygeNUO8lHksOKfua5JZ69UwqIspfQlf27OrVJeJSqhFkpgUU9Xpo7m919RylLI9rHUaZDWGR3/S3/aoYfsmCZi8D5GJq4EsAhZba76LIEaYCJAueVX2RyHcSGVZQFoqp4V7AXwAO2yNVVdpgq4BaAauhvqU8BuCq0j/PVCGS2puossR/IO/KvBkzAaEuE+wr0MKzEEvhWDFfx61X5yDAp3U5e3sGJQzn3P8tqLSDLFLevYSevrjq4JxhOeDedGRPwdkf1RnMS5qq0W7aQ8aFQi4iE0GBFYNlFVE09oFA66HzJVwm1lf4bmqdMSJg8oDtP8XsOYltkiuUih1WRSvO+ZHuIHte9InWM4+jZh8VKO1othr+nVUMHapNq2EuZs+c7ELeOMFiCBpyWhTNoHn85F887rhaKUd6lnePuasErAAb4b7kZO+wVdkMcBE5yU6WKVTUIdOzcbqK9AXL2zia5KyttnFXqCbv3/z+k/t4AfxEr8sor+R2dPzB9W6CL0QMk3Bx7Hq6smtP6u2FWpH4wwu6TEfmnEifjErmWTBdDFscGFV4MLHI30KEWlu2bezbIKuFeKFBEi3hfabafdZsxpNh5NapVOX84J0xkDxFIKatj/RdhUyp0yPd1QczESfgWeoq1Xpw21scQh0Xk84NYAbc=
  - secure: epBMihEWe88nk7XVkhZYfSbiOV5g38suqirLrB8DjgO/ft7DDlwpXDQH7N4oC42Qs55DyU+TY1fHvQdpcVKRxOxduFmv3kWJlbHHfPrPvLALaWYYe1kN8i5qyx5JHDPrUyouR7GohiJT7teeanNS6IsI1FJDsLJW242v/as2ES+sWYt9+lLdj+yKroA4BnikYZKYJ7+RLux85I1mV+Xr5N2cNBo5z+RKailxhWbZ4rMYJwEj1iV7bknQANeusenYFQayS6o/R7IX7Td3YOb+Fa5MechzHFkGuMSJ/D1Ha5hasg3JWnbe4ClNtqaEEHW48z7bpSRi9Fm9LX4c8og3cQv6Y6aeLpQoUFOW4NSU38oJxHq3C0n6LEvYMBr9++vkHjAFPZ9L8Tzs4ICb5dTeUzl1ULkrrequJVEl0f9QYECNKZvB9IZiX8qT+1D55imX61sdvae4W+1LIaWypoJXFl5MBxwzcPb8IpThHm2AYImgwVgVNJ7VHRslbhxaQrmcOdQFWzzB5MtFxNPHPnMY309HhFmFP4iYXZdbZQlNG5vZaOk6Wu+yzb1Vu7j7ayI/SDyLBN9hkKerel4D0oywiH+0bRe4ZfKKFp/ASEhVB8QgySpTCgJxADWTFGRb4P8PbBy80knmC2rpd0OUrfd4Lmpq5VSUbvk6qMrneUcdEf8=
  - secure: m7L/KmWjZYprDZxlLk9QVLvWpS80fv2TUKUWE1ZDmo0fdurwtpIpOp9JYADkfk3vEuQ6au9VI7nzL9yipf+szxXSoQvl1D9mNV4bAfLd0u3zHJCrFzzfnIyBSuD/EqZp5Q0ZcaFXzwMSCsFLRYd6DE5F8rCXD33AVD2GZFaX19AktEN6RobpfYQvuVBE/AVCOYwMcJnEtcqFYN91by5owCWF+2Z9YC9NC6WBqFr7AvmI5xuwxrxmPYZl23EsEa+pIwoUUxKZDvnYTi6Lsdk6sBMKcLU2MaGs1hlPhluBpoppOJw7gsm7zeQdmyq5pGQaJTZlca7ubP1NlKoDbBHTRo5eSVoP0rjv1RxAIATk2O9hApCgn6kwRd8rLP/0UGkpUTnH2KhRCq4pl8PkafvzNVpr4VyZpLTPmHGYq322v7vre8XjYAYT3oHMwZgM9DKwBc8LJzB0LRbXRRn1QMk0emMhVpf9B4pqJv0zjoJav/DtIy1lB4l+dsm0Nn4Iq7uFlsz3JRmFvIY37wsNgV6JvVyJThiedo2Dio60srtLxtw01IiH5VQjHaKlrTR61S2voyArN4IOjpp1wx6WBe1ZPiCeURVbzHN50YySKC3VZJD5wcsIfW6dGAhO9yMNq25p6pOUZn+feKIJ7O6cQwatHuxbb0arcZKRceBizbpEdJc=
before_deploy: git clean -fd && git reset --hard HEAD && go get github.com/karalabe/xgo
  && make semvertagchk && make -j2 release
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: KoJl6jHnAG3TwDiUMo0dXcCHXid7NTkIVgwxMZECW5Jc3b45Hc7WZ+P9N7k7qjkogt3R2FTtdcjs5+I/nph2Xx3QB2PgpXHWGdj0LAQEh8g1cCbc/HV7Ydjex1l5qwrXKE9V+2pCdVEWMYLKC2gXpGtlgOZCZI++o44apukm0VyLueb73Qw9AoZcMF9oYBof7a3HsN82yzXDmF9k7cW3V10vNma/TLAo6o52olaz7KDKdppTfuCVQFmjAaNDEbUi1O2QG6tg+gSuKx4KYmhdt1IaFDBmgypmf7hvvdPXEqZluW8CNSmflb7OSRp7u6v1v0zKlG4HG3LeVq2UcScrGjkori16MpdPZIopkpTeCzKlTOnf7+dmPWcjs9NMpxKIXuAhG7fpLIFEupsDDwzTlwmBZG6vZkUHCfI4q20/+CG/Ck3jQGXUXVowJK8tSckST0ucWkuOg5TB239TLy6QeO3kwvsvNjT++/0poE59/GZsMULU/DzGzmHRfU5xxm0n9TJDhTD6GhtlfjS/NeKSRruVXPeuN+sr5XnUXLMtLnyMoRmC0Oh00G/Dpzq6pXSItZW2et1lXf7wXUEWmWmPX8pahfYVwH4cjfyEZ4ajdoO2IdDMYpgXjDc53JopeX4BkLpUSpRzRjMm3Yb4y6Az0iyv9Y+cXrIhWzFVCluGtOg=
  file:
  - artifacts/sous-darwin-amd64_*.tar.gz
  - artifacts/sous-linux-amd64_*.tar.gz
  on:
    tags: true
  skip_cleanup: true
notifications:
  hipchat:
    on_failure: always
    on_success: change
    template: |-
      Travis: %{message}<br />
      %{repository_slug}#%{build_number} (%{branch} : %{author}):<br />
      <a href="%{compare_url}">%{commit_subject}</a><br />
      Build: <a href="%{build_url}">%{build_number}</a>
    format: html
    rooms:
      secure: MYcyZu5zXfvu72SKPt5vdF/LYtzKdybmL0RIIiiTJzGjb08Cz7LyvyfBBkFc9KWxHT3qK/swUUeCxLHYXHDFfzMDiWYPD+QB7Z2704f4/V8Vg3BjGz2CXlnNC3x1ehj3EbryMfg9C2K/dmYXI7YDjvZwT1iGM/63tMBZSUPE25mfnX6CoIpiIqznMB68JmJzTu9k8BxHKVOkwyvzmKKe7bcG+poiurXM60ly2qUqO11gmT019HOQMMUsxqVUXPoSALhZMArqXQzWG7t/408SGByI7CG1RwGuT8h+iGgsDMH4j30quormEG+y+7VzTjetRFae5BPZ0iCIu11p5atFc2ejNbDVGHdagK7H6hCuPzACWtRHDyVV1ZZ6Bv3pAtId1iCXeHebdagMe5BAsAv6G0Li+6WNQL3o7Tj6wSMPeJ/Zz9XwKHeoFocrERMhfCuhyx/M1mPZPYDVFZ/H4/GiNquDppRxUiCWK61XGmQI0fTY+R0mW6pX9l40oELV1kf6PoJCjYPRJI/kXqTi5x6dfLDctKhrUk662iXSailMtaJJKYREa30OvEaXjNrC0OSw+PTmK9zavVtsSkwkgRnBes1ZlYZnH3VKMGM0mV/L/aKzAAY9xsIuUOl8gvHK3NZ/yUWW58ncVqv+++cEM1ZxuFVuVFtIP/EpV5fc0h0/+Wc=
