sudo: required
services:
- docker
language: go
go:
- 1.7.3
before_install:
- bin/ci-setup
install:
- "./bin/vendor-check"
- "./bin/check-gofmt"
- export SOUS_QA_DESC=${TRAVIS_BUILD_DIR}/${SOUS_QA_DESC}
- sous_qa_setup --compose-dir ./integration/test-registry/ --out-path=$SOUS_QA_DESC
script:
- "make --output-sync=target -j2 travis"
after_success:
- bin/codecov -f /tmp/sous-cover/count_merged.txt
env:
  global:
  - SOUS_QA_DESC=qa_desc.json
  - GIT_AUTHOR_NAME=SousCI
  - GIT_COMMITTER_NAME=SousCI
  - GIT_AUTHOR_EMAIL=sous@nowhere.in.particular.com
  - GIT_COMMITTER_EMAIL=sous@nowhere.in.particular.com
  - DOCKER_VERSION=1.10.1-0~trusty
  - DOCKER_COMPOSE_VERSION=1.6.0
  - secure: jQv4im3Imakryl54Z7qR2BEa1+Gq//sAwo3XP/1J6sSdtBjtOYY1SgdAYh7pVB111HV546vKPJqQ6GsAtHM7tjnVjlF1PabAHEWl/ZP3ZXj3SvuFNaV5j5PmrJvxPlK7nbr0uG6PPspxFkZg+X87GGIyFGCp7F3EWKIU6aX6rEeBbY/greAxISmtGYHrDwK4sQnMXl4+WoagbKwoi16fK94XweU2Etg40rLwtYRdRJTPMdhrinkkkfQ4Jga5uepsmkZFjgZJySgyEzxvVuUuEYHaQreRLHzJBjPXw96tQOGpw4OT5aRJjga6PlEJRp68pC3KPrzW7lQQMMCHpxrauEqR1r1ltg+UD2GIixAT80duOl7mD6aPyx3L04L/bg4u1sI26JyHN34X/mpg9OufE47zSOC48RicSA6y4D+ZyD/dubu626NScnLufAveWaVH/mu5brVZ3ni+8BgVqDW/vfIJTyELegz7DD9wS/xaoUVnAjnTH73efce8bDAaAOvpa4dlkZEcBDU2LjasP735FNh0/sLeVsuwhopMIKPsnpwce1Fxg83ls+KRDqXj8/l67Db5nQqTvsWk3S12nvrgPO1uX/we8fqwUKuLNlnU3befd7KugvUamixGoxlX65etwt4hvFWT11Qfv/IB7JXjLToUAfXm/QpiprEm/VqZWTM=
  - secure: yoQHrMJeCnRumhKPRCvygeNUO8lHksOKfua5JZ69UwqIspfQlf27OrVJeJSqhFkpgUU9Xpo7m919RylLI9rHUaZDWGR3/S3/aoYfsmCZi8D5GJq4EsAhZba76LIEaYCJAueVX2RyHcSGVZQFoqp4V7AXwAO2yNVVdpgq4BaAauhvqU8BuCq0j/PVCGS2puossR/IO/KvBkzAaEuE+wr0MKzEEvhWDFfx61X5yDAp3U5e3sGJQzn3P8tqLSDLFLevYSevrjq4JxhOeDedGRPwdkf1RnMS5qq0W7aQ8aFQi4iE0GBFYNlFVE09oFA66HzJVwm1lf4bmqdMSJg8oDtP8XsOYltkiuUih1WRSvO+ZHuIHte9InWM4+jZh8VKO1othr+nVUMHapNq2EuZs+c7ELeOMFiCBpyWhTNoHn85F887rhaKUd6lnePuasErAAb4b7kZO+wVdkMcBE5yU6WKVTUIdOzcbqK9AXL2zia5KyttnFXqCbv3/z+k/t4AfxEr8sor+R2dPzB9W6CL0QMk3Bx7Hq6smtP6u2FWpH4wwu6TEfmnEifjErmWTBdDFscGFV4MLHI30KEWlu2bezbIKuFeKFBEi3hfabafdZsxpNh5NapVOX84J0xkDxFIKatj/RdhUyp0yPd1QczESfgWeoq1Xpw21scQh0Xk84NYAbc=
before_deploy: git clean -fd && git reset --hard HEAD && go get github.com/karalabe/xgo && make semvertagchk && make --output-sync=target -j2 release
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: KoJl6jHnAG3TwDiUMo0dXcCHXid7NTkIVgwxMZECW5Jc3b45Hc7WZ+P9N7k7qjkogt3R2FTtdcjs5+I/nph2Xx3QB2PgpXHWGdj0LAQEh8g1cCbc/HV7Ydjex1l5qwrXKE9V+2pCdVEWMYLKC2gXpGtlgOZCZI++o44apukm0VyLueb73Qw9AoZcMF9oYBof7a3HsN82yzXDmF9k7cW3V10vNma/TLAo6o52olaz7KDKdppTfuCVQFmjAaNDEbUi1O2QG6tg+gSuKx4KYmhdt1IaFDBmgypmf7hvvdPXEqZluW8CNSmflb7OSRp7u6v1v0zKlG4HG3LeVq2UcScrGjkori16MpdPZIopkpTeCzKlTOnf7+dmPWcjs9NMpxKIXuAhG7fpLIFEupsDDwzTlwmBZG6vZkUHCfI4q20/+CG/Ck3jQGXUXVowJK8tSckST0ucWkuOg5TB239TLy6QeO3kwvsvNjT++/0poE59/GZsMULU/DzGzmHRfU5xxm0n9TJDhTD6GhtlfjS/NeKSRruVXPeuN+sr5XnUXLMtLnyMoRmC0Oh00G/Dpzq6pXSItZW2et1lXf7wXUEWmWmPX8pahfYVwH4cjfyEZ4ajdoO2IdDMYpgXjDc53JopeX4BkLpUSpRzRjMm3Yb4y6Az0iyv9Y+cXrIhWzFVCluGtOg=
  file:
    - "artifacts/sous-darwin-amd64_*.tar.gz"
    - "artifacts/sous-linux-amd64_*.tar.gz"
  on:
    tags: true
  skip_cleanup: true
notifications:
  hipchat:
    on_failure: always
    on_success: change
    template: |-
      Travis: %{message}<br />
      %{repository_slug}#%{build_number} (%{branch} : %{author}):<br />
      <a href="%{compare_url}">%{commit_subject}</a><br />
      Build: <a href="%{build_url}">%{build_number}</a>
    format: html
    rooms:
      secure: MYcyZu5zXfvu72SKPt5vdF/LYtzKdybmL0RIIiiTJzGjb08Cz7LyvyfBBkFc9KWxHT3qK/swUUeCxLHYXHDFfzMDiWYPD+QB7Z2704f4/V8Vg3BjGz2CXlnNC3x1ehj3EbryMfg9C2K/dmYXI7YDjvZwT1iGM/63tMBZSUPE25mfnX6CoIpiIqznMB68JmJzTu9k8BxHKVOkwyvzmKKe7bcG+poiurXM60ly2qUqO11gmT019HOQMMUsxqVUXPoSALhZMArqXQzWG7t/408SGByI7CG1RwGuT8h+iGgsDMH4j30quormEG+y+7VzTjetRFae5BPZ0iCIu11p5atFc2ejNbDVGHdagK7H6hCuPzACWtRHDyVV1ZZ6Bv3pAtId1iCXeHebdagMe5BAsAv6G0Li+6WNQL3o7Tj6wSMPeJ/Zz9XwKHeoFocrERMhfCuhyx/M1mPZPYDVFZ/H4/GiNquDppRxUiCWK61XGmQI0fTY+R0mW6pX9l40oELV1kf6PoJCjYPRJI/kXqTi5x6dfLDctKhrUk662iXSailMtaJJKYREa30OvEaXjNrC0OSw+PTmK9zavVtsSkwkgRnBes1ZlYZnH3VKMGM0mV/L/aKzAAY9xsIuUOl8gvHK3NZ/yUWW58ncVqv+++cEM1ZxuFVuVFtIP/EpV5fc0h0/+Wc=
